# Generated by Django 5.1.7 on 2025-03-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_token',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
